model_name_or_path: /home/dataset-assist-0/czy/wjy/pathvlm_r1_v1_a100/transferred_checkpoints/sft_n3000_seed42_epoch03_step1125
trust_remote_code: true
image_max_pixels: 65536
video_max_pixels: 8192
flash_attn: sdpa
use_cache: false
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: /home/dataset-assist-0/czy/wjy/myr1/configs/deepspeed/ds_z2_gpu_torch_adamw.json
dataset_dir: /home/dataset-assist-0/czy/wjy/pathvlm_r1_v1_a100/runs/stage2_control_sft4000/n1000_seed0042/sft4000_control_rl1000_seed0042_epoch02_20260729_212746/input_data
dataset: pathvlm_sft4000_rl_n1000
template: qwen2_vl
cutoff_len: 512
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
output_dir: /home/dataset-assist-0/czy/wjy/pathvlm_r1_v1_a100/runs/stage2_control_sft4000/n1000_seed0042/sft4000_control_rl1000_seed0042_epoch02_20260729_212746/output
logging_steps: 1
save_strategy: epoch
save_only_model: false
save_total_limit: 2
plot_loss: true
overwrite_output_dir: false
report_to: none
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 2.0e-05
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
gradient_checkpointing: true
disable_gradient_checkpointing: false
optim: adamw_torch_fused
seed: 42
data_seed: 42
ddp_timeout: 180000000
